### ISSUE TITLE
[K8s Contrib CRD] CRD generation failed when a field uses `{}` as default value.

### ISSUE THREAD

**Issue by inoc603** [apple/pkl-pantry#32]
CRD generation will fail when a field uses `{}` as default value.

```
–– Pkl Error ––
Expected value of type `Boolean|Number|Null|String|Dynamic|Typed|Listing`, but got type `Mapping`.
Value: new Mapping {}

39 | typealias JsonSchemaValue = Boolean|Number|Null|String|Dynamic|Typed|Listing
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at org.json_schema.JsonSchema#default (projectpackage://pkg.pkl-lang.org/pkl-pantry/org.json_schema@1.0.0#/JsonSchema.pkl)

101 | default = raw.getOrNull("default")
                ^^^^^^^^^^^^^^^^^^^^^^^^
at org.json_schema.Parser#toJsonSchema.default (projectpackage://pkg.pkl-lang.org/pkl-pantry/org.json_schema@1.0.0#/Parser.pkl)

......
```

A minimal CRD to reproduce the problem:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: example
spec:
  scope: Namespaced
  group: example
  names:
    kind: Example
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            some_map:
              additionalProperties:
                type: string
              default: {}
              type: object
          type: object
```
