### ISSUE TITLE
[K8s Contrib CRD] CRD conversion fails if object default is defined

### ISSUE THREAD

**Issue by mruoss** [apple/pkl-pantry#36]
In the example below there's an object with two fields, `first` and `second`. A default for the entire object is defined as `first: foo`. 

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.example.com
spec:
  group: example.com
  names:
    kind: Foo
    plural: foos
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            first:
              default: foo
              type: string
              enum:
                - foo
                - bar
            second:
              type: string
          type: object
          default:  # <-- defining this leads to the failure
            first: foo
      served: true
      storage: true
```

Converting this using `k8s.contrib.crd@1.0.1` fails, throwing the following error:

```
–– Pkl Error ––
Expected value of type `Boolean|Number|Null|String|Dynamic|Typed|Listing`, but got type `Mapping`.
Value: new Mapping { ["first"] = ? }

39 | typealias JsonSchemaValue = Boolean|Number|Null|String|Dynamic|Typed|Listing
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at org.json_schema.JsonSchema#default (https://github.com/apple/pkl-pantry/blob/org.json_schema@1.0.0/packages/org.json_schema/JsonSchema.pkl#L39-39)

101 | default = raw.getOrNull("default")
                ^^^^^^^^^^^^^^^^^^^^^^^^
at org.json_schema.Parser#toJsonSchema.default (https://github.com/apple/pkl-pantry/blob/org.json_schema@1.0.0/packages/org.json_schema/Parser.pkl#L101-101)

144 | (if (predicate.apply(schema))
           ^^^^^^^^^^^^^^^^^^^^^^^
at org.json_schema.contrib.internal.utils#_findMatchingSubSchemas (https://github.com/apple/pkl-pantry/blob/org.json_schema.contrib@1.0.2/packages/org.json_schema.contrib/internal/utils.pkl#L144-144)

116 | .flatMap((propertyName, schema) -> _findMatchingSubSchemas(schema as JsonSchema, path.add(propertyName), predicate))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at org.json_schema.contrib.internal.utils#findMatchingSchemasInMapping.<function#2> (https://github.com/apple/pkl-pantry/blob/org.json_schema.contrib@1.0.2/packages/org.json_schema.contrib/internal/utils.pkl#L116-116)

113 | m
      ^
at org.json_schema.contrib.internal.utils#findMatchingSchemasInMapping (https://github.com/apple/pkl-pantry/blob/org.json_schema.contrib@1.0.2/packages/org.json_schema.contrib/internal/utils.pkl#L113-116)

148 | + findMatchingSchemasInMapping(schema.properties, path, predicate)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at org.json_schema.contrib.internal.utils#_findMatchingSubSchemas (https://github.com/apple/pkl-pantry/blob/org.json_schema.contrib@1.0.2/packages/org.json_schema.contrib/internal/utils.pkl#L148-148)

177 | _findMatchingSubSchemas(schema, List(), predicate)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at org.json_schema.contrib.internal.utils#findMatchingSubschemas (https://github.com/apple/pkl-pantry/blob/org.json_schema.contrib@1.0.2/packages/org.json_schema.contrib/internal/utils.pkl#L177-177)

351 | utils.findMatchingSubschemas(filteredRootSchema, (elem) -> elem != filteredRootSchema)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at k8s.contrib.crd.internal.ModuleGenerator#convertedSchemas (https://github.com/apple/pkl-pantry/blob/k8s.contrib.crd@1.0.1/packages/k8s.contrib.crd/internal/ModuleGenerator.pkl#L351-351)

122 | moduleTypes: Type.TypeNames = convertedSchemas.map((schema, importAndType) -> Pair(schema, importAndType.type)) + classSchemas
                                    ^^^^^^^^^^^^^^^^
at k8s.contrib.crd.internal.ModuleGenerator#moduleTypes (https://github.com/apple/pkl-pantry/blob/k8s.contrib.crd@1.0.1/packages/k8s.contrib.crd/internal/ModuleGenerator.pkl#L122-122)

126 | let (allTypeNames = moduleTypes)
                          ^^^^^^^^^^^
at k8s.contrib.crd.internal.ModuleGenerator#moduleNode (https://github.com/apple/pkl-pantry/blob/k8s.contrib.crd@1.0.1/packages/k8s.contrib.crd/internal/ModuleGenerator.pkl#L126-126)

143 | ["\(mod.moduleName.split(".").last).pkl"] = mod.moduleNode.output
                                                  ^^^^^^^^^^^^^^
at k8s.contrib.crd.generate#output.files[#1] (https://github.com/apple/pkl-pantry/blob/k8s.contrib.crd@1.0.1/packages/k8s.contrib.crd/generate.pkl#L143-143)

141 | files {
      ^^^^^^^
at k8s.contrib.crd.generate#output.files (https://github.com/apple/pkl-pantry/blob/k8s.contrib.crd@1.0.1/packages/k8s.contrib.crd/generate.pkl#L141-145)
```
