### ISSUE TITLE
[K8s Contrib CRD] Duplicate class definitions in generated module

### ISSUE THREAD

**Issue by mruoss** [apple/pkl-pantry#40]
The example CRD below secifies `.first.some_class` and `.second.some_class`. The CRD generator successfully generates a module. However, the module defines the class `SomeClass` twice which leads to an error upon evaluation.

#### The CRD

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.example.com
spec:
  group: example.com
  names:
    kind: Foo
    plural: foos
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            first:
              type: object
              properties:
                some_class: 
                  type: object
                  properties:
                    foo: 
                      type: string
            second:
              type: object
              properties:
                some_class: 
                  type: object
                  properties:
                    bar: 
                      type: string
          type: object
      served: true
      storage: true
```

#### Resulting PKL

```pkl
/// This module was generated from the CustomResourceDefinition at
/// <file:///Users/mruoss/src/community/pkl/playground/example.yaml>.
module com.example.v1.Foo

extends "package://pkg.pkl-lang.org/pkl-k8s/k8s@1.0.1#/K8sResource.pkl"

import "package://pkg.pkl-lang.org/pkl-k8s/k8s@1.0.1#/apimachinery/pkg/apis/meta/v1/ObjectMeta.pkl"

fixed apiVersion: "example.com/v1"

fixed kind: "Foo"

/// Standard object's metadata.
///
/// More info: <https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata>.
metadata: ObjectMeta?

first: First?

second: Second?

class First {
  some_class: SomeClass?
}

class SomeClass {
  foo: String?
}

class Second {
  some_class: SomeClass?
}

class SomeClass { // <-- second definition of SomeClass
  bar: String?
}
```
