### ISSUE TITLE
[TOML] Renderer never renders maps as inline values

### ISSUE THREAD

**Issue by archer-321** [apple/pkl-pantry#61]
# Context

AFAICT, the current implementation of `toml.Renderer` has code to render map-like elements as [inline tables](https://toml.io/en/v1.0.0#inline-table):
[toml.pkl:146](https://github.com/apple/pkl-pantry/blob/437359005c0c4d2afdac2e2fb191740d3dc0a073/packages/pkl.toml/toml.pkl#L146-L151)

However, the current implementation doesn't seem to use that code, as every type that gets converted to a `Map` ends up rendering as a regular table.

## Suggested change

While inlining small tables generally improves readability, large tables can quickly lead to very long lines if inlined.
To determine whether a table would be small enough to inline, the implementation could
* define a maximum number of keys above which it generates a regular table instead.
  * This could be too inaccurate, as long values like strings or even nested tables might lead to long inline tables regardless.
* render any map fully inline and compare it with a maximum line length.
  * This would be accurate, but especially for larger tables, this might lead to performance problems
* add an annotation that makes the renderer inline the table.
  * If the annotation is specific to `pkl.toml`, this would force general packages to depend on a rendering-specific package. Moreover, it would be impossible to inline third-party types.

I understand that none of the suggestions above are ideal, but considering no issue exists for this segment of dead code, I opened this issue anyway.

## Example

The examples below were generated using `pkl.toml@1.0.0`, and `pkl --version` yields `0.26.0-dev+47f161a` (I built the native binary locally).

The following example contains a mapping of usernames to the user's UID and GID:

```pkl
import "package://pkg.pkl-lang.org/pkl-pantry/pkl.toml@1.0.0#/toml.pkl"

output {
    renderer = new toml.Renderer {}
}

users {
    foo {
        uid = 1000
        gid = 1000
    }
    cups {
        uid = 209
        gid = 209
    }
    nobody {
        uid = 65534
        gid = 65534
    }
}
```

Currently, it produces the following document:

```toml
[users.foo]
uid = 1000
gid = 1000

[users.cups]
uid = 209
gid = 209

[users.nobody]
uid = 65534
gid = 65534
```

However, the same data could be expressed in TOML using inline tables:

```toml
[users]
foo = { uid = 1000, gid = 1000 }
cups = { uid = 209, gid = 209 }
nobody = { uid = 65534, gid = 65534 }
```

While the verbose tables that the current implementation generates are still readable in this basic example, the additional tables quickly become a problem if many small objects are part of another table. For example, the following version renders as five tables and an array of tables (two `[[]]` tables).

<details>
<summary><b>Second example</b></summary>

```pkl
import "package://pkg.pkl-lang.org/pkl-pantry/pkl.toml@1.0.0#/toml.pkl"

output {
    renderer = new toml.Renderer {}
}


machines = new Listing {
    new {
        hostname = "office"
        users {
            foo {
                uid = 1000
                gid = 1000
            }
            cups {
                uid = 209
                gid = 209
            }
            nobody {
                uid = 65534
                gid = 65534
            }
        }
    }
    new {
        hostname = "server"
        users {
            admin {
                uid = 1000
                gid = 1000
            }
            named {
                uid = 40
                gid = 40
            }
        }
    }
}
```

This generates:

```toml
[[machines]]
hostname = "office"

[machines.users.foo]
uid = 1000
gid = 1000

[machines.users.cups]
uid = 209
gid = 209

[machines.users.nobody]
uid = 65534
gid = 65534

[[machines]]
hostname = "server"

[machines.users.admin]
uid = 1000
gid = 1000

[machines.users.named]
uid = 40
gid = 40
```

</details>

A version using inline tables could represent the same data using two tables and an array of tables or even just the array of tables if the `users` table is inlined as well (even though that would lead to very long lines).

**Comment by bioball** [comment]
The TOML renderer will output inline tables in some circumstances, for example, if it is producing a mixed object:

```
import "package://pkg.pkl-lang.org/pkl-pantry/pkl.toml@1.0.0#/toml.pkl"

output {
    renderer = new toml.Renderer {}
}
```

**Comment by archer-321** [comment]
> The TOML renderer will output inline tables in some circumstances, for example, if it is producing a mixed object

Oh, I missed mixed-type listings (or other mixed-type objects for which `toMap()` returns an empty map). Looking at the code again, it makes sense why those would end up inlined.
I assume TOML's syntax wouldn't allow for a non-inline table definition in arrays that can't be represented as an array of tables.

However, this implies objects with properties/entries can never generate inline tables.

> What is the motivation for wanting inline tables? FWIW: trying to make rendered output textually equivalent to some output is somewhat of a never-ending battle. Generally, you should trust that Pkl is producing data that is semantically equivalent to your desired output.

I'm currently exploring Pkl as a "configuration preprocessor" with validation at configuration time. While the generated configuration files would not be edited manually, having human-readable configuration files would allow manual inspection even if the source `.pkl` files aren't available.

That said, one reason I opened this issue was that I considered the inline table code to be unused. With mixed-type tables even requiring this syntax, this issue is reduced to the question of how much Pkl focuses on human-readable output.

**Comment by bioball** [comment]
> That said, one reason I opened this issue was that I considered the inline table code to be unused. With mixed-type arrays even requiring this syntax, this issue is reduced to the question of how much Pkl focuses on human-readable output.

We definitely want to produce human-readable output. Readability is a little subjective, though; I don't know that this is harder to read:

```toml
[users.foo]
uid = 1000
gid = 1000

[users.cups]
uid = 209
gid = 209

[users.nobody]
uid = 65534
gid = 65534
```

Do you have a suggestion for what the heuristic should be? At what point should the renderer emit inline tables?
